.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli - CLI-first, agent-native Islamic prayer times tool


.SH SYNOPSIS
\fBprayertime-cli [flags]\fP


.SH DESCRIPTION
CLI-first, agent-native Islamic prayer times tool


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for prayertime-cli

.PP
\fB--json\fP[=false]
	Emit JSON output to stdout


.SH SEE ALSO
\fBprayertime-cli-locations(1)\fP, \fBprayertime-cli-times(1)\fP, \fBprayertime-cli-version(1)\fP
