.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli-times - Fetch daily prayer times and countdowns


.SH SYNOPSIS
\fBprayertime-cli times [flags]\fP


.SH DESCRIPTION
Fetch daily prayer times and countdowns


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for times


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	Emit JSON output to stdout


.SH SEE ALSO
\fBprayertime-cli(1)\fP, \fBprayertime-cli-times-countdown(1)\fP, \fBprayertime-cli-times-get(1)\fP
