.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli - CLI-first, agent-native Islamic prayer times tool


.SH SYNOPSIS
\fBprayertime-cli [flags]\fP


.SH DESCRIPTION
Stateless prayer-time CLI for agents, shell scripts, and direct terminal use.

.PP
MVP 1 has no persisted default location. Every times query must provide --query PLACE or both --lat and --lon.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for prayertime-cli

.PP
\fB--json\fP[=false]
	Emit structured JSON to stdout


.SH EXAMPLE
.EX
prayertime-cli locations search --query "Springfield" --country-code US --limit 3 --json
prayertime-cli times get --query Istanbul --json
prayertime-cli times countdown --query Istanbul --target next-prayer --json
.EE


.SH SEE ALSO
\fBprayertime-cli-locations(1)\fP, \fBprayertime-cli-times(1)\fP, \fBprayertime-cli-version(1)\fP
