.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli-locations - Search locations before requesting prayer times


.SH SYNOPSIS
\fBprayertime-cli locations [flags]\fP


.SH DESCRIPTION
Search locations before requesting prayer times


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for locations


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	Emit JSON output to stdout


.SH SEE ALSO
\fBprayertime-cli(1)\fP, \fBprayertime-cli-locations-search(1)\fP
