.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli-times-countdown - Calculate seconds and minutes remaining until a target prayer


.SH SYNOPSIS
\fBprayertime-cli times countdown [flags]\fP


.SH DESCRIPTION
Calculate remaining time until the next prayer or a named prayer target.

.PP
Use --target next-prayer for generic "next ezan" questions. Canonical targets are English, while Turkish semantic aliases such as iftar, aksam, and yatsi are also accepted.


.SH OPTIONS
\fB--at\fP=""
	Optional RFC3339 timestamp to evaluate countdown from

.PP
\fB--country-code\fP=""
	Optional ISO country code filter

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for countdown

.PP
\fB--lat\fP=0
	Latitude coordinate. Use with --lon instead of --query

.PP
\fB--lon\fP=0
	Longitude coordinate. Use with --lat instead of --query

.PP
\fB--query\fP=""
	Place name to resolve. Required unless --lat and --lon are set

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Emit only remaining seconds

.PP
\fB--target\fP=""
	Target prayer. Use next-prayer for generic countdowns; iftar and yatsi are accepted aliases


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	Emit structured JSON to stdout


.SH EXAMPLE
.EX
prayertime-cli times countdown --query Istanbul --target next-prayer --json
prayertime-cli times countdown --query Istanbul --target iftar --quiet
prayertime-cli times countdown --lat 41.01384 --lon 28.94966 --target asr --at 2026-03-07T12:00:00+03:00 --json
.EE


.SH SEE ALSO
\fBprayertime-cli-times(1)\fP
