.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli-locations-search - Search for a place and return candidate coordinates


.SH SYNOPSIS
\fBprayertime-cli locations search [flags]\fP


.SH DESCRIPTION
Search for a place before requesting prayer times.

.PP
Use this command first when a user-supplied place may be ambiguous, incomplete, or misspelled.


.SH OPTIONS
\fB--country-code\fP=""
	Optional ISO country code filter

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search

.PP
\fB--limit\fP=5
	Maximum number of results to return

.PP
\fB--query\fP=""
	Place name to search


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	Emit structured JSON to stdout


.SH EXAMPLE
.EX
prayertime-cli locations search --query Istanbul
prayertime-cli locations search --query Springfield --country-code US --limit 3 --json
prayertime-cli locations search --query Istnbul --json
.EE


.SH SEE ALSO
\fBprayertime-cli-locations(1)\fP
