.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli-version - Print the CLI version


.SH SYNOPSIS
\fBprayertime-cli version [flags]\fP


.SH DESCRIPTION
Print the CLI version


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	Emit structured JSON to stdout


.SH SEE ALSO
\fBprayertime-cli(1)\fP
