.nh
.TH "prayertime-cli" "1" "Mar 2026" "prayertime-cli" ""

.SH NAME
prayertime-cli-locations-search - Search for a place and return candidate coordinates


.SH SYNOPSIS
\fBprayertime-cli locations search [flags]\fP


.SH DESCRIPTION
Resolve a place query into candidate locations and canonical coordinates.

.PP
Input rules:
  - --query is required.
  - --country-code is optional and should be used to narrow ambiguous place names.
  - --limit controls the maximum number of returned candidates.

.PP
Output:
  - --output text prints numbered candidates with coordinates and timezone.
  - --output json prints query, count, and structured candidates including display_name.
  - --output value is not supported for location search.


.SH OPTIONS
\fB--country-code\fP=""
	Optional ISO country code filter

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for search

.PP
\fB--limit\fP=5
	Maximum number of results to return

.PP
\fB--query\fP=""
	Place name to search


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	Shortcut for --output json

.PP
\fB--output\fP="text"
	Output mode: text, json, or value


.SH EXAMPLE
.EX
prayertime-cli locations search --query Istanbul
prayertime-cli locations search --query London --country-code GB --output json
.EE


.SH SEE ALSO
\fBprayertime-cli-locations(1)\fP
